submit_ticket:
    path:     /tickets/submit
    defaults: { _controller: AppBundle:Tickets:submitTicket }

ticket_submission_successful:
    path:     /tickets/submit/success
    defaults: { _controller: AppBundle:Tickets:ticketSubmissionSuccessful }

latest_submitted_tickets:
#    path:     /tickets/latest
    path:     /
    defaults: { _controller: AppBundle:Tickets:latestSubmittedTickets }

hot_in_trend_tickets:
    path:     /tickets/hot
    defaults: { _controller: AppBundle:Tickets:hotTickets }

view_ticket_details:
    path:     /tickets/{ticketId}/details
    defaults: { _controller: AppBundle:Tickets:viewTicketDetails }

make_an_offer:
    path:     /offers/make/{ticketId}
    defaults: { _controller: AppBundle:Offers:makeAnOffer }

offer_successfully_made:
    path:     /offers/success
    defaults: { _controller: AppBundle:Offers:offerSuccessfullyMade }

view_offers_for_ticket:
    path:     /offers/{ticketId}/
    defaults: { _controller: AppBundle:Offers:viewOffersForTicket }

member_sign_up:
    path:     /members/signup
    methods: ['GET', 'POST']
    defaults: { _controller: AppBundle:Members:signUp }

member_sign_up_successful:
    path:     /members/signup/successful
    defaults: { _controller: AppBundle:Members:signUpSuccessful }

member_sign_in:
    path:     /members/signin
    defaults: { _controller: AppBundle:Members:signIn }

member_sign_out:
    path:     /members/signout
    defaults: { _controller: AppBundle:Members:signOut }

admin.list_all_tickets:
  path: /admin/tickets/all
  defaults: { _controller: AppBundle:Admin\Tickets:listAllTickets }
